/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: forwardobj.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "forwardobj.pb-c.h"
void   forward__object__init
                     (ForwardObject         *message)
{
  static ForwardObject init_value = FORWARD__OBJECT__INIT;
  *message = init_value;
}
size_t forward__object__get_packed_size
                     (const ForwardObject *message)
{
  assert(message->base.descriptor == &forward__object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t forward__object__pack
                     (const ForwardObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &forward__object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t forward__object__pack_to_buffer
                     (const ForwardObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &forward__object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ForwardObject *
       forward__object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ForwardObject *)
     protobuf_c_message_unpack (&forward__object__descriptor,
                                allocator, len, data);
}
void   forward__object__free_unpacked
                     (ForwardObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &forward__object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor forward__object__field_descriptors[6] =
{
  {
    "sessionid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ForwardObject, sessionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ForwardObject, cmd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "strdata",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ForwardObject, strdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intdata",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ForwardObject, has_intdata),
    offsetof(ForwardObject, intdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buffdata",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ForwardObject, has_buffdata),
    offsetof(ForwardObject, buffdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ForwardObject, direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned forward__object__field_indices_by_name[] = {
  4,   /* field[4] = buffdata */
  1,   /* field[1] = cmd */
  5,   /* field[5] = direction */
  3,   /* field[3] = intdata */
  0,   /* field[0] = sessionid */
  2,   /* field[2] = strdata */
};
static const ProtobufCIntRange forward__object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor forward__object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Forward_Object",
  "ForwardObject",
  "ForwardObject",
  "",
  sizeof(ForwardObject),
  6,
  forward__object__field_descriptors,
  forward__object__field_indices_by_name,
  1,  forward__object__number_ranges,
  (ProtobufCMessageInit) forward__object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
