#!/bin/sh
trap "rm -f bundle.pad bundle.hv bundle.ck bundle.img xaa xab; exit" INT TERM EXIT
bundle_bin=$1
cur_dir=`pwd`

if [ $# -eq 0 ];then
	echo "Please enter the parameter"
	exit
fi

rm -f  bundle.pad bundle.hv bundle.ck bundle.img xaa xab

vhead_size=`ls -l $bundle_bin | awk '{print $5}'`

if [ $vhead_size -le 5122 ];then
	echo "file too small"
	exit
fi 

let "vpad_size=$vhead_size-4096-1024-2"


dd if=$bundle_bin bs=1 skip=$vpad_size count=4096 of=bundle.pad > /dev/null 2>&1

ver_cnt=`cat bundle.pad | grep "version" | wc -l`
alg_cnt=`cat bundle.pad | grep "algorithm" | wc -l`

if [ $ver_cnt -gt 0 ];then
	cat bundle.pad | jq '.version' | xargs echo "DPI Version:"
else
	echo "DPI version:"
fi

if [ $alg_cnt -gt 0 ];then
	cat bundle.pad | jq '.algorithm' | xargs echo "algorithm:"
else
	echo "algorithm:"
fi

let "ckpad_size=$vpad_size+4096"
dd if=$bundle_bin bs=1 skip=$ckpad_size count=1024 of=bundle.ck > /dev/null 2>&1
hexstr=`hexdump bundle.ck  | grep 0000000 | sed -e "s/0000000 //" | sed -e "s/ //g"`

i=0
len=${#hexstr}

while [ $i -lt $len ]
do
        temp=`expr $i \% 2`
	temp_4=`expr $i \% 4`
	if [ $temp_4 -lt 2 ];then
        	pre_ck=${pre_ck}${hexstr:$i:1}
	else
	        if [ $temp -eq 0 ]; then
        	        sufix_ck=${hexstr:$i:1}
        	else
                	sufix_ck=${sufix_ck}${hexstr:$i:1}

				checksum=${checksum}${pre_ck}${sufix_ck}
			pre_ck=""
			sufix_ck=""
        	fi
		
	fi
	let i++
done


split -b $ckpad_size ${bundle_bin}
newck=`md5sum xaa`
newck=`echo $newck | sed -e "s/ xaa$//"`


echo "Binary file checksum :"$checksum
echo "Calculated checksum  :"$newck

if [ $newck == $checksum ]; then
	echo "Image is correct"
else
	echo "Image is incorrect!!!"
fi
let "hvpad_size=$ckpad_size+1024"

dd if=$bundle_bin bs=1 skip=$hvpad_size count=2 of=bundle.hv > /dev/null 2>&1

hexhv=`hexdump bundle.hv  | grep 0000000 | sed -e "s/0000000 //" | sed -e "s/ //g"`

checksum=""

i=0
len=${#hexhv}

while [ $i -lt $len ]
do
        temp=`expr $i \% 2`
	temp_4=`expr $i \% 4`
	if [ $temp_4 -lt 2 ];then
        	pre_ck=${pre_ck}${hexhv:$i:1}
	else
	        if [ $temp -eq 0 ]; then
        	        sufix_ck=${hexhv:$i:1}
        	else
                	sufix_ck=${sufix_ck}${hexhv:$i:1}
				checksum=${checksum}${pre_ck}${sufix_ck}				
				pre_ck=""
				sufix_ck=""
        	fi
		
	fi
	let i++
done


echo "Head version: "$checksum


rm -f  bundle.pad bundle.hv bundle.ck bundle.img xaa xab

